# Generated by Django 2.1.5 on 2023-03-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20230317_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='url',
            new_name='Url',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='views',
            new_name='Views',
        ),
    ]
