# Generated by Django 2.1.5 on 2023-03-17 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20230317_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='Url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='Views',
            new_name='views',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
